name = "orders-cron"
main = "src/index.ts"
compatibility_date = "2025-10-06"

[triggers]
crons = ["*/1 * * * *"]

[vars]
API_URL = "https://whale-futures.pages.dev/api/notification"
ORIGIN  = "https://mexc-leaders.pages.dev"
REFERER = "https://mexc-leaders.pages.dev/"
X_API_KEY = "6c516352be6"